### ISSUE TITLE
Unable to read multiple MODIFY records in single file

### ISSUE THREAD

**Issue by codymaust** [jcasale/LdifHelper#3]
Thanks for this project, it helped me out a lot.
I ran into this issue with our specific data set and made changes to accomodate

Example - these are two distinct change-modify entries. LdifHelper fails to pick these up, and throws an exception while reading.

```
dn: CN=Ada Lovelace,OU=users,DC=company,DC=com
changetype: modify
add: description
description: another updated description


dn: CN=Niklaus Wirth,OU=users,DC=company,DC=com
changetype: modify
add: description
description: description update
```

https://github.com/jcasale/LdifHelper/pull/2 was opened for this

**Comment by jcasale** [comment]
The spec states the following for a modify change type, known as a `mod-spec`:

```
change-modify            = "modify"             SEP *mod-spec
mod-spec                 = ("add:" / "delete:" / "replace:")
                           FILL AttributeDescription SEP
                           *attrval-spec
                           "-" SEP
```

A modify statement(s) begins and *ends* with a `SEP` character, and does not allow for a newline between consecutive `mod-spec` statements in the same `changerecord`.

As a result, the exception you receive is due to noncompliant input.
